### ISSUE TITLE
Logic to (dis)allow to resize window differs on Windows vs Linux/Darwin

### ISSUE THREAD

**Issue by pierrejoye** [wailsapp/wails#1049]
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**

**To Reproduce**

Simple example code:

```
package main

import (
	"embed"
	"log"

	"github.com/wailsapp/wails/v2/pkg/options/mac"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/logger"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/windows"
)

//go:embed frontend/src
var assets embed.FS

//go:embed build/appicon.png
var icon []byte

func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:     "Your-POS",
		Width:     720,
		Height:    570,
		MinWidth:  720,
		MinHeight: 570,
		//MaxWidth:          1280,
		//MaxHeight:         740,
		DisableResize:     false,
		Fullscreen:        false,
		Frameless:         true,
		StartHidden:       false,
		HideWindowOnClose: false,
		RGBA:              &options.RGBA{R: 33, G: 37, B: 43, A: 255},
		Assets:            assets,
		LogLevel:          logger.DEBUG,
		OnStartup:         app.startup,
		OnDomReady:        app.domReady,
		OnShutdown:        app.shutdown,
		Bind: []interface{}{
			app,
		},
		// Windows platform specific options
		Windows: &windows.Options{
			WebviewIsTransparent: false,
			WindowIsTranslucent:  false,
			DisableWindowIcon:    false,
		},
		Mac: &mac.Options{
			TitleBar:             mac.TitleBarHiddenInset(),
			WebviewIsTransparent: true,
			WindowIsTranslucent:  true,
			About: &mac.AboutInfo{
				Title:   "Vanilla Template",
				Message: "Part of the Wails projects",
				Icon:    icon,
			},
		},
	})

	if err != nil {
		log.Fatal(err)
	}
}
```

By default the window is resizable, if I am not mistaken.

However, using the example above, I have to enable frameless to allow to resize the window (from the edges, using the mouse).

I think it is a bug (or doc issue :). This line causes it I suppose:

https://github.com/wailsapp/wails/blob/6d9a195830ef9e83452695e243bc0771091ea1f1/v2/internal/frontend/desktop/windows/window.go#L60

```
	if appoptions.Frameless == false && !appoptions.Fullscreen {
		result.EnableMaxButton(!appoptions.DisableResize)
		result.EnableSizable(!appoptions.DisableResize) // Here DisableResize is false, so it becomes true if frameless is false and not in fullcreen
		result.SetMinSize(appoptions.MinWidth, appoptions.MinHeight)
		result.SetMaxSize(appoptions.MaxWidth, appoptions.MaxHeight)
	}
```

**Expected behaviour**
Ability to resize the window by default.

**Screenshots**
NA

**System Details**
```

Wails CLI v2.0.0-beta.27


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.5
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       96.0.1054.62
npm             N/A             Installed       8.3.0
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/


```

**Additional context**

(https://github.com/wailsapp/wails/blob/6d9a195830ef9e83452695e243bc0771091ea1f1/v2/internal/frontend/desktop/windows/window.go#L60) seems to be the culprit.

Other platforms do not have this logic:

Linux:
https://github.com/wailsapp/wails/blob/6d9a195830ef9e83452695e243bc0771091ea1f1/v2/internal/frontend/desktop/linux/window.go#L248
```
	result.SetResizable(!appoptions.DisableResize)
```

Mac:
https://github.com/wailsapp/wails/blob/6d9a195830ef9e83452695e243bc0771091ea1f1/v2/internal/frontend/desktop/darwin/window.go#L49
```
resizable := bool2Cint(!frontendOptions.DisableResize)
```

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment]
This is absolutely a nice find. Looks like I made a mistake. Line 60 should be outside of that if statement. Will fix tmorrow unless you fancy testing that and raising a PR?

**Comment by pierrejoye** [comment]
will do a PR, I wanted to be sure it is a bug first :)

**Comment by pierrejoye** [comment]
PR opened.

I am not sure whether we should still not allow it when fullscreen is enabled. Maybe at some point we allow one (or an app can handle it itself) to switch between fullcreen, maximized etc at runtime rather than at build time. For now I just moved out the resize option out of this scope.

**Comment by pierrejoye** [comment]
Thank you! :)

**Comment by taigrr** [comment]
Is this closeable?

**Comment by leaanthony** [comment]
No. The issue is still there. I think this may have been a red herring. The problem, i suspect, is that the JS hacks to enable resizing in frameless windows are interfering with the standard window.

**Comment by pierrejoye** [comment]
That bug was only about the go part of it though  :)

I can test again next week as I did not look at all at the JS part, given i
met the issue in go.

**Comment by leaanthony** [comment]
There's a fix in `v2.0.0-beta.28`. It turns out it was a change I made to an underlying library that had a faulty HITTEST check. There's maybe more to the issue than just that, but this makes resize work by default. Let me know how you get on 👍

**Comment by stffabi** [comment]
Unfortunately I think `v2.0.0-beta.28` is still not quite right in all cases on windows.

- Frameless = false
  - DisableResize = false => works as expected
  - DisableResize = true => works as expected
- Frameless = true
  - DisableResize = false => window is resizable, but there's a small white titlebar shown, which wasn't the case in older releases
  - DisableResize = true => window is still resizable

Let's consider the case `Frameless == true && DisableResize == true` where the window is still resizable: The `EnableSizable` method uses `ToggleStyle`, whose logic is quite strange in the case for setting the value to false. If the value to set is false, it will just xor the current value with the style. For frameless windows the default style has `w32.WS_THICKFRAME` not set and therefore the result will be that the `w32.WS_THICKFRAME` bit is set.
So `ToggleStyle` does the following, if the value is true the bit will always be set to true and if the value is false it will toggle the current value. A better way would be to rename `ToggleStyle` to `SetStyle` and in the false case one should use `&^=` to clear the bit. This would fix this case.

Let's consider the case `Frameless == true && DisableResize == false`: Unfortunately there's now way to hide the small white titlebar it or change the color if the style bit `w32.WS_THICKFRAME` is set. That's way in prior versions the `result.EnableSizable(!appoptions.DisableResize)` wasn't called for frameless windows. In order to enable resizing for frameless in the case `appoptions.DisableResize == false`, the resizing has been activated and initiated by the frontend with the `resize:` messages.
Therefore `result.EnableSizable(!appoptions.DisableResize)` should be at least constraint to `Frameless == false` windows.

**Comment by leaanthony** [comment]
Thanks for deep diving this issue @stffabi - my time has been really limited lately 🙏
