### ISSUE TITLE
V2 can be simpler by using Nix

### ISSUE THREAD

**Issue by diogox** [wailsapp/wails#1118]
This is more of a suggestion, but I feel like v2 can be heavily simplified by "enforcing" the usage of the Nix package manager.

Nix works on all linux distros (afaik) *and* MacOS.

With a wails nix package, you can have it installed, with all the dependencies scoped to the package (without polluting the user space), on pretty much everywhere but Windows, and you wouldn't need to have as much of the installation logic in Wails.

There are downsides ofc, but I just thought I'd leave the suggestion here. I'm trying to package wails for my NixOS, and I'll share the result when I manage to make it work :)

**Comment by ianmjones** [comment]
I'm a big fan of Nix/Nixpkgs/NixOS too, but I'm not sure enforcing usage of Nixpkgs would be a good idea. Mostly because it's unfortunately not as popular as other packaging formats yet, but also that it does have some issues on some Linux distros occasionally (I've hit them), and on macOS it can also sometimes have problems depending on what's being packaged and some things out of your control.

Nixpkgs does have a bit of a learning curve too, which makes it a little tricky as a default target for Linux Wails apps.

But, I do think it would be great to have the ability to generate a `default.nix` for your Wails app via some command. I would love that. And the option of making a `flake.nix` would be great too.

And I especially like that you're working on packaging `wails` (v2?) for Nixpkgs/NixOS, I'd use that!

**Comment by leaanthony** [comment]
@ianmjones has submitted a PR for getting it in Nix. Thanks for opening this issue!
