### ISSUE TITLE
Lag with Vuetify Template

### ISSUE THREAD

**Issue by ariefsn** [wailsapp/wails#128]
Hi,
i've just create project with vuetify templates.
after build it's become lag (ie. when open Modal or Navigation Drawer).
it's normal or not?
if not, how to make that animate be smoothly??

**Comment by bh90210** [comment]
Hi @ariefsn, no it is not. Can you please share your platform, go & npm version?

**Comment by ariefsn** [comment]
> Hi @ariefsn, no it is not. Can you please share your platform, go & npm version?

Thanks for your response,, I use
Windows 10 Pro x64
npm v8.12.0
go v1.12.5

**Comment by bh90210** [comment]
No worries :) 

I could ask if you've you tried using react or "simple" vue templates to see if the problem persists, but I am making a wild guess that this is a windows related issue, I really can not help with this one, so please wait until main dev comes :+1:

**Comment by leaanthony** [comment]
Hi there. Thanks for taking the time to report this! I actually noticed this on my Windows installation when testing but wondered whether it was just my machine. The reality is that for MSHTML (IE), [Vuetify need to use polyfills](https://vuetifyjs.com/en/getting-started/quick-start#ie11-safari-9-support). I'm assuming that this is the reason it's laggy. 

**Potentially, Vuetify isn't a great solution for Windows.** 

However, there's some really good news: due to the amazing work of @bh90210, react is now an option. So whilst I understand your pain with Vuetify, it's really a limitation of the framework.

**Comment by ariefsn** [comment]
> No worries :)
> 
> I could ask if you've you tried using react or "simple" vue templates to see if the problem persists, but I am making a wild guess that this is a windows related issue, I really can not help with this one, so please wait until main dev comes 👍

> Hi there. Thanks for taking the time to report this! I actually noticed this on my Windows installation when testing but wondered whether it was just my machine. The reality is that for MSHTML (IE), [Vuetify need to use polyfills](https://vuetifyjs.com/en/getting-started/quick-start#ie11-safari-9-support). I'm assuming that this is the reason it's laggy.
> 
> **Potentially, Vuetify isn't a great solution for Windows.**
> 
> However, there's some really good news: due to the amazing work of @bh90210, react is now an option. So whilst I understand your pain with Vuetify, it's really a limitation of the Vuetify framework.

oh ok, so the conclude are change to react or use linux, right??
thanks all 👍🏻👍🏻👍🏻

**Comment by leaanthony** [comment]
Well, you can still use Vue, just maybe not Vuetify. Our template master has also been busy on Angular so there are certainly plenty of options! :-)
