### ISSUE TITLE
I tried to use WebSocket in Vue and found it unsuccessful

### ISSUE THREAD

**Issue by LunckyB** [wailsapp/wails#1293]
I tried to use WebSocket in Vue and found it unsuccessful, Does Wails not support it?
![1648531685(1)](https://user-images.githubusercontent.com/82591823/160539645-00dcbb23-b0b6-4e8b-b54f-0dc5eb9e5980.jpg)

**Comment by raguay** [comment]
I believe it's the same issue as Tauri and Wails: websockets is only allows from a https source. Therefore, you can't use the ws:// designation. It's an issue with the built in browser for the operating system that Wails makes use of.

**Comment by LunckyB** [comment]
> I believe it's the same issue as Tauri and Wails: websockets is only allows from a https source. Therefore, you can't use the ws:// designation. It's an issue with the built in browser for the operating system that Wails makes use of. I think the best solution is to create the functionality in the application go code and use signals to alert the front-end.

Thank you for your reply. I now use Gorilla/Websocket in Wails

**Comment by misitebao** [comment]
I strongly recommend that the front-end part is only used to display UI, js is only used to handle front-end interaction logic and call Go, other business logic and communication should be done by Go, otherwise it will make the Wails application look like a shell, but in fact It can do more than that.

**Comment by leaanthony** [comment]
☝️ This is the recommended best practice.

**Comment by sebastian0x62** [comment]
Especially when the logical part is in Go, interactive response in the GUI is often necessary. WebSockets is default for such channels. But because it's way simpler, I personally switched to server-sent events for such topics. It has limitations compared to WebSockets, but works very well for some event transfer.

**Comment by yangpeng1994** [comment]
I'm also developing 'webssh' recently, which just solves this problem
vue3：` const webSocket = new WebSocket(WebSocketAddr)`
go：`"github.com/gorilla/websocket"`

**Comment by leaanthony** [comment]
Sounds like there's a workaround. Closing.

**Comment by s00500** [comment]
hm... quite an odd issue, I have an application built with a lot of interactivity based on htmx websocket... any tips for a simple fix here ?

**Comment by leaanthony** [comment]
There's a plugin for HTMX for this. I don't have the link handy but a google search should help

**Comment by s00500** [comment]
Hm not sure that was understood as I ment it (I am already using the htmx-ws plugin), I was trying to do this while using my server as the asset handler. This seems to not work as a websocket connection to the asset handler will not work. (I assume the wails:// protocol does something similar to file:// ?)

Meanwhile I am using a actual server to work around this for now.

**Comment by leaanthony** [comment]
Yeah, this is the best approach. I'm really keen for someone to build a secure local server v3 Service that fetches an auth key using IPC then uses that key to round trip via a local server
