### ISSUE TITLE
Asset Handler takes a long time to hand-off to custom asset handler in dev mode

### ISSUE THREAD

**Issue by selvinortiz** [wailsapp/wails#1380]
### Description

It looks like the experimental implementation of custom asset handler support is slow while developing and it also seems to block at each request.

Here is a video to show this behavior on an app I'm building: https://youtu.be/4E4JPaCGcXg

### To Reproduce

Run `wails dev` on any app that uses a custom asset handler and has a view that loads multiple local files.

### Expected behaviour

All requests should be handed off to the custom handler right away and all requests should be handled concurrently.

### Screenshots

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/4E4JPaCGcXg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### System Details

```shell
Wails CLI v2.0.0-beta.36


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.3
ID:             199506
Go Version:     go1.18
Platform:       darwin
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.36

Dependency                      Package Name    Status    Version
----------                      ------------    ------    -------
xcode command line tools        N/A             Installed 2395
npm                             N/A             Installed 8.3.1
*upx                            N/A             Available
*nsis                           N/A             Installed v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
```
```


### Additional context

_No response_

**Comment by stffabi** [comment]
Hi @selvindev thanks for your report.

Yeah we currently only process one request after the other no concurrency at least not on Windows and not on Darwin. Linux is currently the only platform which processes up to 10 requests in parallel. This might change in the near future. According to your report, I assume it's working fine in a production build?

Nevertheless it should not take that long for simple requests when using `wails dev`. The problem is caused by the fact that the `AssetServer` first tries to serve the file from the assets and then if not found it will hand the request over to the `AssetHandler`. Since there is some retry logic for missing files in `wails dev` this now causes the delay of about 5s you see. The retry logic has been introduced to have some resiliency when an `frontend:dev:watcher` rebuilds the frontend and wails already has restarted but not all files have been rebuilt yet.

I think we might remove that logic since it was more of a workaround for `vite` (and similar concepts) as we didn't have support for the external dev server. @leaanthony what do you think?

**Comment by leaanthony** [comment]
I added in `go` before the internal serveHTTP method and concurrency seemed to work ok. This was on windows

**Comment by stffabi** [comment]
> I added in go before the internal serveHTTP method and concurrency seemed to work ok. This was on windows

Should we really process it unbounded? On Linux we have limited it to 10 parallel requests by using 10 workers. I think we should be consistent across the platforms if we introduce parallel processing. So either unbounded on all platforms for bounded on all platforms. 
I'm not sure if parallel processing works on all platforms without changes, e.g. on Darwin we manipulate a `NSMutableDictionary` in the response path, so that might not be Thread-Safe.

Adding concurrency won't help for the processing duration of the request when using `wails dev`. The request would still take 5s to be completed. What do you think about removing the retry logic?

**Comment by leaanthony** [comment]
Yeah, I didn't have time to test too deeply so there may be a bunch of issues with it. It's an experimental feature so I don't think it's a problem to not be consistent across the platforms at the moment. I'm also keen to look at what makes this thread unsafe and seeing if there's a fix for that.

**Comment by stffabi** [comment]
I'm not sure if we can make the processing parallel just for the AssetsHandler. To have a fully working solution I think we need to make changes to the way the `processRequest` methods are getting called and how the interaction with the native code works. Like for Linux where we start multiple processRequest workers and increasing the refcount. And as soon was we have changes there, it will also affect the processing of all assets not just the AssetsHandler.

I've seen you added a "thumbs-up" to my post, does that mean you are ok with removing the retry logic?

**Comment by leaanthony** [comment]
Yes, sorry. All good. I'll have a bit more time tonight to look into this properly 👍

**Comment by leaanthony** [comment]
@selvindev - Are you using this exclusively for reading files from disk?

**Comment by leaanthony** [comment]
I think that's the problem we need to solve 👍

**Comment by stffabi** [comment]
I still think we should solve the problem that `AssetsHandler` requests take 5s when using `wails dev`. Otherwise `AssetsHandler` are not usable in a `dev` experience.

**Comment by stffabi** [comment]
@leaanthony is there a reason to still keep this reload logic since we now have fully support for external dev servers?

**Comment by stffabi** [comment]
I've created a draft PR to propose "disabling retry logic when AssetsHandler are in use".

**Comment by leaanthony** [comment]
Sorry for being slow on this. Yeah I'm happy to remove the reload logic. I think, if you choose to not use the supported dev framework then you're just going to have to press F5 😂

**Comment by leaanthony** [comment]
I've also set the PR to auto merge, so when you're happy with it @stffabi , just approve it (if not, @selvindev can approve) and it should merge.
