### ISSUE TITLE
golang to ts type conversion error

### ISSUE THREAD

**Issue by r0ckysec** [wailsapp/wails#1389]
### Description

Interface to ts type conversion error implemented by golang

```
func (b *B) AddB(data interface{}) interface{} {
    ... ...
}
```

after conversion
B.d.ts
```
...
export function AddB(arg1:number):Promise<number>;
...
```

type is number????, Shouldn't it be object？？？

### To Reproduce

-

### Expected behaviour

Interface to ts type conversion error implemented by golang

```
func (b *B) AddB(data interface{}) interface{} {
    ... ...
}
```

after conversion
B.d.ts
```
...
export function AddB(arg1:number):Promise<number>;
...
```

type is number????, Shouldn't it be object？？？

### Screenshots

vuln.go
![image](https://user-images.githubusercontent.com/44518337/167574587-ebb5e360-c019-4a63-962c-e87c3df8a128.png)

Vuln.d.ts
![image](https://user-images.githubusercontent.com/44518337/167574618-98ae9997-2f80-4e36-bc46-3e4d65eb048b.png)

### System Details

```shell
wails doctor
Wails CLI v2.0.0-beta.36


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.3.1
ID:		199506
Go Version:	go1.17.6
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.36

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.5.1
*upx 				N/A		Available
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment]
Yeah nice 😃 should be a 5m fix

**Comment by leaanthony** [comment]
Fixed on master: https://github.com/wailsapp/wails/commit/55115742c10654a6fe4439d62095ed8aa1b7b2e8

**Comment by r0ckysec** [comment]
perfect, thanks！！

**Comment by lambdajack** [comment]
I somewhat hesitantly say that I think this may still be broken @leaanthony @r0ckysec 

I have tried following the instructions [https://wails.io/docs/guides/bleeding-edge](https://wails.io/docs/guides/bleeding-edge) but still no joy.

I have also tried pulling `master` and building my own binary, then using that binary directly to generate/build/dev a new project. The binary works, but the issue remains.

**I say _hesitantly_ because of the following:** 

after looking at the issue for some time I realised that my installations and fresh binaries did not appear to be using the function that you committed to at 5511574. 

![Screenshot from 2022-05-14 03-29-40](https://user-images.githubusercontent.com/69592559/168407720-ff30bf07-0b32-4559-b305-1063aecb7bc5.png)

^^ I changed them to literally output complete rubbish because I could not work out what was going on, and then rebuilt the binary. The binary STILL WORKED? The issue remained about converting `interface{}` but the project inited, dev server ran, build compiled etc. All conversion like string, int, struct etc all worked. All from a binary with `wails/v2/internal/binding/generate.go` looking like that ^^

Am I going insane? 

I should mention that I tried this enough times to think I'm not insane, and on two fresh vms with the same result.

I'll have another look at it when it's not 3:30am!

**Comment by leaanthony** [comment]
You did change your project's `go.mod` to use your clone of master right?

**Comment by leaanthony** [comment]
I think you've not updated your project's `go.mod` to use your local clone of master.

**Comment by lambdajack** [comment]
Ohhhhhh no..  😅. You're right. Just awoken to see I was replacing in the master go.mod, not the projects! _"Am I going insane?"_ **yes**. I was testing in a project generated inside the wails clone folder iteself (because laziness) and just automatically kept using the go.mod at the bottom of the vscode explorer...

Sorry for the long message about nothing!

**Comment by leaanthony** [comment]
No problem Jack! Glad it's sorted for you. Let us know what you build 👍
