### ISSUE TITLE
Support Distribution 'Zorin'

### ISSUE THREAD

**Issue by amalshaji** [wailsapp/wails#148]
**Description**
Distribution 'Zorin' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.10.4 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | Zorin |
| Distribution Version   | 15 |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
hey there @amalshaji 

Zorin at the time is not supported but since it is ubuntu based distro then should be possible to make it work. We will look into it. @leaanthony 

Other than that Wails needs go 1.12 in order to work https://wails.app/quick_start.html#prerequisites 
so while we look in expanding support for zorin could you please update your go version?

**Comment by leaanthony** [comment]
Thanks for making the request! Do you know what version of Ubuntu it tracks to? It wasn't clear from the site. Thanks.

**Comment by bh90210** [comment]
Ubuntu 18.04.2
https://www.omgubuntu.co.uk/2019/06/zorin-os-15-linux

**Comment by leaanthony** [comment]
Hi @amalshaji. Could you please run `wails update -pre` to update to v0.17.1-pre and let us know if it works for Zorin. Many thanks!

**Comment by amalshaji** [comment]
Thank you for your email. I'm impressed with your work on wails app.

**Comment by leaanthony** [comment]
Did you test v0.17.1 @amalshaji ? Does it fix your issue?

**Comment by amalshaji** [comment]
Yes. Changing to v0.17.1 -pre worked for me. Thanks for the support.

**Comment by leaanthony** [comment]
Thanks for the feedback!!
