### ISSUE TITLE
Common Clipboard Support

### ISSUE THREAD

**Issue by leaanthony** [wailsapp/wails#1743]
It would be good to provide an API for getting and setting the clipboard in both Go and JS.

**Comment by csterritt** [comment]
I second this -- and I haven't forgotten to document the current situation, with respect to what I found, I've just... forgotten :-)

Sorry. I did look at doing a doc update, and I *think* what I need to do is do a new version? It seemed like Docusaurus wouldn't even recognize the existence of a new file unless I did one. Is that right? Is there a better way to add a new file?

Thanks!

**Comment by misitebao** [comment]
We can create a new package to develop extension functions, similar to [""](https://github.com/vueuse/vueuse) for Vue.

**Comment by Lyimmi** [comment]
I don't know what is the status of this ticket, but I looked into this.
If it is enough for us to handle text on the clipboard, I think this could be solved relatively easily.

I think we could create two runtime functions with "text" in their name to leave the option open for images etc. in the future.
 - GetClipboardText()
 - SetClipboardText()

On windows we could use [something like this.](https://github.com/atotto/clipboard/blob/master/clipboard_windows.go) (didn't test it my self)
On macOS we could use [something like this.](https://github.com/atotto/clipboard/blob/master/clipboard_darwin.go) (didn't test it my self)
On Linux of course it's more complicated, because of X11 and Wayland, however we could use GTK as a "middleware" and with that we could solve it on both window manager without any user installable dependency.

My working Linux experiment, uses gtk to get/set the current clipboard on X11 and Wayland as well.

```C
static gchar* GetClipboardText() {
	GtkClipboard *clip = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
	return gtk_clipboard_wait_for_text(clip);
}

static void SetClipboardText(gchar* text) {
	GtkClipboard *clip = gtk_clipboard_get(GDK_SELECTION_CLIPBOARD);
	gtk_clipboard_set_text(clip, text, -1);
}

```

```golang
func (f *Frontend) GetClipboardText() string {
	var text string
	var wg sync.WaitGroup
	wg.Add(1)
	invokeOnMainThread(func() {
		ctxt := C.GetClipboardText()
		defer C.free(unsafe.Pointer(ctxt))
		text = C.GoString(ctxt)
		wg.Done()
	})
	wg.Wait()
	return text
}

func (f *Frontend) SetClipboardText(text string) {
	invokeOnMainThread(func() {
		ctxt := (*C.gchar)(C.CString(text))
		defer C.free(unsafe.Pointer(ctxt))
		C.SetClipboardText(ctxt)
	})
}
```
Interestingly this solution interferes with every single screen recorder on Linux... So can't show any demo. Something to think about, I guess.

**Comment by Lyimmi** [comment]
I created a branch with the text clipboard functions on the go side.

Tested on Windows and Linux, for some reason my macOS VM won't start, so I could not test it on mac.


https://github.com/Lyimmi/wails/commits/feature/1743_common_clipboard_support

If it's ok, I could try to add it to the js runtime, than create a PR for it.
