### ISSUE TITLE
Go routines that do not return a value have incorrect JS generated types

### ISSUE THREAD

**Issue by SheetJSDev** [wailsapp/wails#1818]
### Description

A Go routine that does not return a value should have a type that returns `Promise<void>` instead of `void`.

### To Reproduce

1) add to app.go:

```
func (a *App) Noop() {}
```

### Expected behaviour

The generated type should be

```js
export function Noop():Promise<void>;
```

### System Details

```shell
n/a
```

**Comment by brys0** [comment]
Every function GO -> JS will be a promise, if it's marked as it, or not. It's a side effect of using the built in IPC of the browser frontend.

**Comment by SheetJSDev** [comment]
The bug is that Wails generates incorrect types in `frontend/wailsjs/go/main/App.d.ts`.  For example:

```go
func (a *App) Noop() {}
```

Wails generates the following type in `App.d.ts`:

```ts
export function Noop():void;
```

It should be generating the following type:

```ts
export function Noop(): Promise<void>;
```

(#1821 is the fix)

**Comment by leaanthony** [comment]
There's certainly some history on this and different people feel differently about it: https://github.com/wailsapp/wails/issues/1355
I personally feel that having all methods returning a promise as standard is preferable but @ianmjones had valid reasons for thinking this was undesirable. Let's start that discussion again. 

One solution is to have a project preference to choose between a return type of `Promise<void>` and `void` and it generates based on that. My concern is making an API breaking change which seems inevitable.

**Comment by SheetJSDev** [comment]
Ironically the example from #1355 is the exact reason for proposing the change.

```go
// ShowError displays an error message in a desktop dialog.
func (a *App) ShowError(title string, message string) {
	_, _ = runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.ErrorDialog,
		Title:   title,
		Message: message,
	})
}
```

From JS, if the type is

```ts
export function ShowError(arg1:string,arg2:string):Promise<void>;
```

Then you can `await` for the user response before performing an action:

```js
async function doSomething() {
  try {
    /* try to do some action */
  } catch(e) {
    await ShowError("Error", `An error has occurred: ${e.message}.  This application will now quit`);
    /* do some JS-related cleanup */
    await Quit(); // func (a *App) Quit() { runtime.Quit(a.ctx); }
  }
}
```

Without the await, the error will not be displayed:

```js
async function doSomething() {
  try {
    /* try to do some action */
  } catch(e) {
    ShowError("Error", `An error has occurred: ${e.message}.  This application will now quit`);
    /* if cleanup is fast, the quit function will be run before the error popup */
    await Quit(); // func (a *App) Quit() { runtime.Quit(a.ctx); }
  }
}
```

**Comment by ianmjones** [comment]
@leaanthony I'm not clear on a detail, let me ask a couple of questions.

In @SheetJSDev's examples where the Go func `ShowError` does not even return `error`, if there was ...

1. ... an error in the JavaScript side in trying to call back to the Go side (IPC broken), would an error be thrown by the WailsJS framework?
2. ... an error in the Go side when WailsGo somehow failed before even calling `ShowError`, would an error be thrown by the WailsJS framework?
3. ... an error in Go side while `ShowError` was in progress causes some sort of failure (I guess it'd have to be a panic as there is no `error` to return), would an error be thrown by the WailsJS framework?

**Comment by SheetJSDev** [comment]
The questions are interesting but unrelated to the issue.

Here's a complete example using a `fetch` that fails:

1) create a new svelte-ts app:

```bash
wails init -n wails-await -t svelte-ts
cd wails-await
```

2) Add the following to `app.go`:

```go
// after the import
import ( "github.com/wailsapp/wails/v2/pkg/runtime" )

// at the bottom
// ShowError displays an error message in a desktop dialog.
func (a *App) ShowError(title string, message string) {
	_, _ = runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		Type:    runtime.ErrorDialog,
		Title:   title,
		Message: message,
	})
}

func (a *App) Quit() { runtime.Quit(a.ctx); }
```

3) In `frontend/src/App.svelte`, add the following in the `<script>` block:

```
import { onMount } from 'svelte';

onMount(async() => {
  try {
    const f = await fetch("https://nonexistent.sheetjs.com");
    if(f.status != 200) throw new Error(`Received unexpected status code ${f.status}`);
  } catch(e) {
    await window['go']['main']['App']['ShowError']("Authentication Error", `Unable to authenticate: ${e.message} ! This application will now exit`);
    await window['go']['main']['App']['Quit']();
  }
});
```

The app will try to fetch, fail, show an error dialog, and quit when the user clicks OK.

4) Build the app and run it:

```bash
wails build
open build/bin/wails-await.app ## macOS
```

You will see the error message.  Clicking "OK" will close the app.

5) remove the two await keywords in `App.svelte`:

```js
onMount(async() => {
  try {
    const f = await fetch("https://nonexistent.sheetjs.com");
    if(f.status != 200) throw new Error(`Received unexpected status code ${f.status}`);
  } catch(e) {
    window['go']['main']['App']['ShowError']("Authentication Error", `Unable to authenticate: ${e.message} ! This application will now exit`);
    window['go']['main']['App']['Quit']();
  }
});
```

6) Build the app and run it:

```bash
wails build
open build/bin/wails-await.app ## macOS
```

There is a race between the dialog and the quit.  Locally, over 25 app runs, the dialog never showed up.

**Comment by leaanthony** [comment]
Good questions @ianmjones.
I think the issue boils down to this: if you don't return a promise, then you don't know when that method has finished regardless of whether it returns something. But I remember you made an argument against it. It may have been something along the lines of "I don't care when it finishes, but I do care that I need to handle these promises anyway"... Perhaps typescript was complaining?

**Comment by ianmjones** [comment]
> The questions are interesting but unrelated to the issue.

I think you may have missed the point of my questions. Sorry about that, my fault, I was time constrained. They're to fish out whether there is a case for always returning a `Promise` because there's a chance of an error being thrown even if the Go function isn't intending to return an `error` or any other result.

If there is a chance that the internals of Wails may throw an error that should really be caught at the JS side, then sure, we need all calls to the backend to return a `Promise`.

If however Wails doesn't throw an error when the Go func doesn't have a return type, but instead just panics and dies, or otherwise has no means of throwing an error in various scenarios if the called function has no return, regardless of whether the JS signature uses a `Promise`, then what's the point in forcing that useless `Promise`?

I understand that the way you're trying to use a Go function that has no return and then doing something in response is going to fail if there's no `Promise`. My question is, why not add a return type to your Go func? A boolean or error would likely work.

Maybe I'm missing something here though. Is there a scenario where you can't add a return type to the Go func but must still `await` it?

I explain my reasoning for not wanting a `Promise` in response to Lea's question...

> I think the issue boils down to this: if you don't return a promise, then you don't know when that method has finished regardless of whether it returns something.

My theory is that if you need to wait for something to happen, then surely your function should return something?

If you specify a return value, even if it's simply an `error` type that will hopefully be `nil`, then you get a `Promise` and can `async/await`. If the only return type is `error`, doesn't Wails rejig things to `Promise<void>` anyway?

In my `ShowError` example above I've already handled the fact that there was an error, there's nothing more to be done, the app isn't going to quit or anything, I just need to inform the user in a native "in your face" way they can't ignore. The fact that they've clicked the OK button or otherwise closed the dialog is irrelevant as there's nothing else to do, the main app window is happily doing its thing.

I don't want the main app's UI to block and potentially stop updating because there's dismissible notice dialog sitting on the desktop somewhere.

In other scenarios I may have a longish process to kick off that I definitely don't want to wait for. I'm happy for the Go function to do its thing either silently and then the app checks on its progress via some other means, or gets told about its status via events. Either way, the main app just keeps on truckin'.

> Perhaps Typescript was complaining?

Sort of, even though I didn't want to use `async/await` or `then()` etc the IDE was not happy, and forced me to handle the `Promise` that I didn't expect.

It's quite a while ago now, it may have even be a Svelte compiler error saying that I had to deal with the result, can't remember.

> There must have been something annoying about it as I think it's possible to just ignore the promise.

How, without blocking somewhere?

**Comment by SheetJSDev** [comment]
Continuing with the example, this is the generated function:

```js
export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}
```

`window['go']['main']['App']['ShowError'](arg1, arg2);` returns a Promise, so `ShowError` also returns a Promise.  The current type `export function ShowError(arg1:string,arg2:string):void;` is not consistent with the actual function.  If type correctness is sacrificed, that should be clearly documented.

JS Note: If a JavaScript function has a return type, [the `void` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) is the standard type-safe way of ignoring the result:

```js
void ShowError(...); // does not await, passes strict type checks
```

**Comment by ianmjones** [comment]
Thanks @SheetJSDev.

I agree, if Wails always sets things up so that a `Promise` is used for the calls regardless of whether there is something to be returned or not, then the generated JS/TS should reflect that.

That's what I was (clumsily) trying to get at with my questions about errors, if there's a `Promise` anyway, then the frontend should know about it.

At least there will be consistent behaviour too.

**Comment by leaanthony** [comment]
Awesome. Thank you everyone for your time and thoughts. Let's add that back in.
