### ISSUE TITLE
Waiting for runtime.Event to finish and get the value....

### ISSUE THREAD

**Issue by glitchedgitz** [wailsapp/wails#1823]
### Is your feature request related to a problem? Please describe.

Hey there, First of all, awesome creation!!

### Summary
I want to get value from JS before moving on in a golang function but `runtime.EventsOnce` is always a goroutine.

### Details
Everything is async...
- I will receive some `text` in my `golang func`,
- I want to send the `text` to frontend and edit the text
- then send it back to golang and the
- sending this back to server

### Golang Code
I modified the code for easy understanding....
```golang

	server.OnText().Do( func(text string) string { //func from another library
                        updatedText := ""
			textId := // Generated textid for runtime event.... So it reach to right func scope
                        
                        // Send text to frontend
			runtime.EventsEmit(a.ctx, "update_text", text, textId)
                       
                       // Get updated text from frontend
			runtime.EventsOnce(a.ctx, textId, func(results ...interface{}) {
                               // We got updated text here
                               updatedText = //extracted from resutts
                               print(updatedText) //here we got updated text
			})
                        
                         print(updatedText) //this print empty string
                         
                         // But I want to use and return updated value here...
                         // As runtime.EventsOnce is thread func... I can't get the updated value
                         
                         return updatedText //return not updated value
		})
```

### Describe the solution you'd like

Is there any way to achieve this in wails?

If not, can we have something to get this? Something where the runtime function can wait until called...
`runtime.Wait()` or something like `runtime.EventsGet()` to wait unitl get hte value from JS.

**Comment by Lyimmi** [comment]
Hi, I think you could use a sync.waitGroup to wait for the "response" event.

Or create a channel, run the events in a goroutine that way you could use a select() for timing out.

**Comment by giteshnxtlvl** [comment]
Hey @Lyimmi,
Well, I tried that before but that doesn't work, now I recheck and figure out another line was messed up.
Haha, Thanks for reminding me!

**Comment by Lyimmi** [comment]
Happy to help, by the way this is what I was thinking about.

```golang
res := make(chan string)
runtime.EventsEmit(a.ctx, "update_text", "hello")
runtime.EventsOnce(a.ctx, "update_text_response", func(results ...interface{}) {
    res <- results[0].(string)
})
select {
case r := <-res:
    return r
case <-time.After(time.Second * 5):
    return "no text was sent"
}
```

**Comment by leaanthony** [comment]
Events are async by nature. Calls are sync but calling into JS is difficult because JS is async by default. For 99% of applications that should be fine as most of your processing logic should be in Go. If you need sync calls to JS then I'd look to see if there's a better way of achieving the same outcome. For most scenarios, the frontend should be a presentation layer but I understand this is not always the case. The use of events in Go will allow you to do what you need:

Go:
```
// Start process in JS
runtime.EventsEmit("start")
runtime.EventsOn("end", func(returnvalues...interface{}) {
   // Do more things
})
```

JS:
```
runtime.EventsOn("start", () => {
  // Do processing
  runtime.EventsEmit("end");
});
```

**Comment by giteshnxtlvl** [comment]
Hey @Lyimmi, 
I was too using this `runtime.EventsOnce(a.ctx, "update_text_response"` as well but because of a previous error it wasn't working, so I thought maybe `runtime.Events` are not limited to func scope that's why I am getting wrong data values... later I found out it's a goroutine. And after your first msg, I was about to test the same and it's working fine.

And thanks you for the go-channel example, I literally forgot that as I am prog after 1 year gap...

@leaanthony Yup that's how I am using it right now.
