### ISSUE TITLE
The latest version of walls uses EventsOnMultiple to report an error. EventsOnMultiple cannot be found!

### ISSUE THREAD

**Issue by Esword618** [wailsapp/wails#1872]
### Description

I want to update the progress bar. I used event, but an error occurred when using eventon. EventsOnMultiple could not be found. This is the fault of my test report.
I tried to solve it, but there was nothing I could do
Here is my go code.
```
func (a *App) Test() {

	for {
		var UUU = U{
			Eval: []string{
				"console.log('hello world')",
			},
		}
		TesTChan <- UUU
		fmt.Println(UUU)
		runtime.EventsEmit(a.ctx, "test", <-TesTChan)
	}
}

// domReady is called after the front-end dom has been loaded
// domReady 在前端Dom加载完毕后调用
func (a *App) domReady(ctx context.Context) {
	go a.Test()
	// Add your action here
	// 在这里添加你的操作
}
```
This is the js code in vue3 ts.
```
function Test(info: any) {
  console.log("----->", info);
  try {
    if (info.Eval){
      for (const n of info.Eval){
        eval(info)
      }
    }
  }catch (err) {
    console.error(err)
  }
}
```
onMounted(() => {
  EventsOn("test", Test);
});

### To Reproduce

no

### Expected behaviour

no

### Screenshots

![Q4X S 9ODJ9F9}UVVO5DVZL](https://user-images.githubusercontent.com/73058062/191297633-3f81c157-612b-4de0-a3f8-fdcafb8d0553.jpg)

### System Details

```shell
windows 11
```

**Comment by leaanthony** [comment]
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- Please include the output of `wails doctor`

**Comment by z1youRA** [comment]
I met the same issue with @Esword618. The source code is in my [repository](https://github.com/z1youRA/McCoffee).
Once the project is built, everything works fine. But after refreshing the page for a couple of times, the web page will become blank and won't reset unless you rebuild the whole project.

My problem is solved by using createWebHashHistory() instead of createWebHistory() in my router.

**Comment by yllhwa** [comment]
windows.runtime is not injected in webHistory(window.runtime===undefined)
But I failed to find out where the runtime is injected in wails.

**Comment by Esword618** [comment]
> I met the same issue with @Esword618. The source code is in my [repository](https://github.com/z1youRA/McCoffee). Once the project is built, everything works fine. But after switching tabs and refreshing the page for a couple of times, the web page will become blank and won't reset unless you rebuild the whole project.
> 
> My problem is solved by using createWebHashHistory() instead of createWebHistory() in my router.

Wow, this really solves my problem. Thank you.

**Comment by yllhwa** [comment]
For who find this issue:
I read the source code and find this
https://github.com/wailsapp/wails/blob/e9b2c15664fdfcd00c570a508895349c6d2f58fe/v2/internal/frontend/assetserver/assetserver.go#L82-L100
Wails will inject `ipc.js` only when `path=="","/","/index.html"`. So you can only use the hash mode router.
I think this is the right approach, otherwise we need to configure the route separately(just like in nginx).
Actually, this point has been mentioned in the [docs](https://wails.io/docs/next/guides/routing/) but I didn't notice that😭.

**Comment by leaanthony** [comment]
Correct @yllhwa - this is not a bug and has nothing to do with `EventsOnMultiple` 👍 Feel free to reopen if there is still an issue. Cheers.

**Comment by hlt-tlh** [comment]
> I met the same issue with @Esword618. The source code is in my [repository](https://github.com/z1youRA/McCoffee). Once the project is built, everything works fine. But after switching tabs and refreshing the page for a couple of times, the web page will become blank and won't reset unless you rebuild the whole project.
> 
> My problem is solved by using createWebHashHistory() instead of createWebHistory() in my router.

Oh Man ！and you！are truly hero！
