### ISSUE TITLE
error Embed twitch

### ISSUE THREAD

**Issue by longjin1991** [wailsapp/wails#2026]
### Description

I embed twitch video to app wails, code:

<div id="twitch-embed">

<script src="[https://player.twitch.tv/js/embed/v1.js"></script>

<script type="text/javascript">
new Twitch.Player("twitch-embed", {
video: "1621322762",

parent: ['wails.localhost', window.location.host],
});
</script>

### To Reproduce

when run: wails dev.
it normal operation, show video and play it.
when run: wails build
it successful, but video twitch not show, not view.
console in devtool error:
Refused to frame 'https://player.twitch.tv/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://wails.localhost/".

### Expected behaviour

i want when run wails build, twitch video show and play normal.

### Screenshots

https://imgur.com/a/T1ZEVYj

### System Details

```shell
System
------
OS:             Windows 10 Pro for Workstations
Version:        2009 (Build: 19045)
ID:             22H2
Go Version:     go1.19.2
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       107.0.1418.24
npm             N/A             Installed       8.19.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

### Additional context

i think the problem comes from the url: https://wails.localhost/
how to change url start:https://wails.localhost/ to example: http:/localhost:1234/
thank you.

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this issue.

Unfortunately I don’t see a way we could support that in a production build. On Linux and macOS we have to use a custom scheme to serve the embedded assets, which is “wails://wails/“. On Windows this was not possible in the early days, so as a workaround Wails is currently using “http://wails.localhost/”, but since this is now supported by WebView2 we are going to switch that probably soon to have a consistent behaviour.

There are several discussions on the twitch dev forum about developers that can’t use the player in a iOS WkWebView app, where one also needs to use a custom scheme: https://discuss.dev.twitch.tv/t/embedded-player-within-ios-web-based-mobile-app-e-g-ionic-not-working/36227
