### ISSUE TITLE
Request a document page for Mac App Store Submission Guide

### ISSUE THREAD

**Issue by tony9527167** [wailsapp/wails#2028]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

something likes https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide

### Self-service

- [ ] I'd be willing to address this documentation request myself.

**Comment by leaanthony** [comment]
Perhaps @achhabra2 could provide some insight into his experience on this?

**Comment by achhabra2** [comment]
Is this just for Mac App store or signing macOS binaries in general? Because the process is different and it definitely tripped me up a bit as you have to add entitlements, etc. I can take a stab at writing something brief specific to wails, but won't cover the general how to set up your Apple developer account / certificate stuff as that's pretty well documented.

**Comment by leaanthony** [comment]
Thanks @achhabra2 🙏 I think the signing part is reasonably well covered in the guide we have.
