### ISSUE TITLE
Support Web MIDI API in Wails Desktop Apps

### ISSUE THREAD

**Issue by Insulince** [wailsapp/wails#2055]
### Is your feature request related to a problem? Please describe.

The [Web MIDI API](https://developer.mozilla.org/en-US/docs/Web/API/Web_MIDI_API) is a suite of functionality that allows JavaScript to interface with a connected MIDI device. The entrance to this API is `navigator.requestMIDIAccess` which Wails Apps do not appear to support. Google Chrome supports it (as do some other, but not all other, browsers) but when running as a standalone desktop app, Wails' web engine does not appear to support it (verified using the console in a running wails app and checking for `navigator.requestMIDIAccess` which was `undefined`).

### Describe the solution you'd like

I would like for Wails to support the Web MIDI API and `navigator.requestMIDIAccess` so that I can run my application stand-alone without a browser as intended. I don't know what this involves to make this happen, but it's a real bummer that I have to run this through Chrome to make it work instead of standalone. Still, better that there is some solution than none.

### Describe alternatives you've considered

Running the application through Google Chrome which does support the Web MIDI API and `navigator.requestMIDIAccess` allows MIDI devices to connect and interface with JavaScript properly. I do not know if there is another way to interface with MIDI devices that is currently supported, but from what I have read, the Web MIDI API is the intended way.

### Additional context

I am working on a desktop application for training one's ability to read sheet music. It displays a musical note like what you would see on a piece of sheet music and prompts you to guess what it is. Your guess can be clicked, typed, or most importantly, _keyed in on a MIDI keyboard_.

My issue arises from how you set up a JavaScript application to read from a MIDI device. The current way you do that is through the Web MIDI API by invoking `navigator.requestMIDIAccess`. [Here is the spec](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/requestMIDIAccess) for that function. One thing to note is that it specifies that you must be in a secure context for it to be available, which you can check via `window.isSecureContext`. Running this in the Wails app console reports that it **is** a secure context, so if this function were supported it _would_ be available.

This function is supported in Google Chrome which I have been using to test my code since Wails lets you use a browser against localhost in addition to just the standalone application if you wish. When I check under Chrome's console for `navigator.requestMIDIAccess`, the console returns a valid and recognized function that the browser implements. If I do the same using the standalone app that gets spun up by Wails, it's console reports that `navigator.requestMIDIAccess` is `undefined`.

This isn't completely unprecedented, I also found that Mozilla Firefox does not support this function either ( apparently it is supported on nightly builds, just not the current stable release), and I am not sure if it's because it's new or experimental or anything like that, but it is worth noting that the Web MIDI API is also supported in more than just Google Chrome.

I don't know what the backing web engine is for Wails, I checked `navigator.userAgent` in Wails' console and it just reported that it's `wails.io`, which isn't terribly clear. So, if it's based on Firefox somehow, that may explain the lack of support for this function.

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this enhancement request.

Wails is using 3 different WebView engines depending on the platform you are using, for Windows WebView2 (based on Edge/Chromium) for macOS on WkWebView (based on WebKit) and for Linux on WebKitGTK (also based on WebKit).

Linux: It seems like WebKitGTK and WebKitCore doesn't support this API and it's not planned: https://github.com/WebKit/WebKit/blob/cd41ef8a9c116a68b994797254d08b2824bc2072/Source/WebCore/features.json#L1070-L1078

macOS: We can't support more than wat Safari normally does, since WkWebView is using the same engine (basically WebKit with some apple customisation), and it seems like Safari doesn't support the Midi API.

Windows: Just tested the `navigator. requestMIDIAccess` and it seems like it's supported there.

Unfortunately that's all we can do. Wails is by design using the platform specific WebView engines, which makes is possible to distribute an app without having to distribute a full browser like Electron. The drawback of this is that there are some limitations depending on platform one is targeting.
If one needs the same behaviour across all platforms one is better served with something like Electron.

**Comment by Insulince** [comment]
Thank you for the clarifications! Your explanations, while disappointing to hear, make perfect sense. This explains why my development environment of MacOS was not able to support this API. Unfortunately, this may mean that I have to move away from Wails for this project, but it's a satisfactory answer for this issue nonetheless. Closing now!
