### ISSUE TITLE
Support for Vendor Builds

### ISSUE THREAD

**Issue by moloch--** [wailsapp/wails#2127]
### Is your feature request related to a problem? Please describe.

`wails build` does not support vendoring (i.e., `go build -mod=vendor ...`) I've worked around the limitation by using the `-compiler` flag with a shim bash script, but it would be nice to have this built into the wails CLI.

### Describe the solution you'd like

A native `wails build` CLI flag to enable vendor builds:

```
wails build -mod=vendor ...
```

**Comment by leaanthony** [comment]
Thanks for opening this. Is this something you're willing to build?

**Comment by moloch--** [comment]
I can probably take a crack at it.

**Comment by stffabi** [comment]
IIRC since Go 1.14 the `go build` should automatically detect the vendor dir and activate `-mod=vendor`. So it should transparently work without needing to change anything in Wails. This seems to work in several of my projects where I'm also using vendoring.

It would be very interesting to find out why it doesn't work in your case. Do you probably have something like `GOFLAGS=-mod=readonly` in your env or go env?

**Comment by moloch--** [comment]
Hrm, the issue came up in a CI worker, but now that I'm thinking about it, it may have been the `go mod tidy` that cause the problem. I disabled wails' go mod tidy at the same time I added the `-mod=vendor` flag.

**Comment by moloch--** [comment]
Confirmed flag not needed, cheers!
