### ISSUE TITLE
wails build error 0xc0000139

### ISSUE THREAD

**Issue by BigCatGit** [wailsapp/wails#2232]
### Description

PS C:\Users\Administrator\Desktop\Test> wails dector
Wails CLI v2.2.0

Available commands:

   build      Builds the application
   init       Initialise a new Wails project
   doctor     Diagnose your environment
   dev        Development mode
Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.19.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.2.0

Dependency      Package Name    Status          Version      
----------      ------------    ------          -------      
WebView2        N/A             Installed       108.0.1462.54
npm             N/A             Installed       Active code page: 65001
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

PS C:\Users\Administrator\Desktop\Test> wails build
Wails CLI v2.2.0

App Type:               desktop
Platforms:              windows/amd64
Compiler:               D:\Dev\Go\bin\go.exe
Skip Bindings:          false
Build Mode:             Production
Frontend Directory:     C:\Users\Administrator\Desktop\Test\frontend
Obfuscated:             false
Skip Frontend:          false
Compress:               false
Package:                true
Clean Bin Dir:          false
LDFlags:                ""
Tags:                   []
Race Detector:          false

Building target: windows/amd64
------------------------------
  - Generating bindings: Error: 

exit status 0xc0000139

ERROR: 

exit status 0xc0000139

### To Reproduce

wails build

### Expected behaviour

build success

### System Details

```shell
win10 21h1
```

**Comment by BigCatGit** [comment]
应该是第三方库不兼容

**Comment by mholt** [comment]
For future searchers:

After several hours of troubleshooting, I figured out that this error is caused by the binary trying to load external libraries (like DLLs) and not finding them.

In my case, the problem had nothing to do with Wails. But it _looks_ like it does, because `go build` worked -- even the same command with the same flags that Wails uses both when it generates bindings, and again when it builds the actual app.

The program may compile fine. But Wails will also _run_ your program to generate the bindings (this I did not know before). That is where the error comes from: it's a runtime error, because these are dynamically-linked libraries (linked at runtime).

I used Process Monitor (procmon) from Sysinternals Suite (free download from Microsoft) to discover a lot of CreateFile calls that were trying to open various DLLs. Many times in repetitively, but at different paths. I found that each attempt was defined by the value of the PATH environment variable.

When I looked up what the PATH was in System Properties, I found that the mingw folder _was in fact in the path_ and what's more, I even found the same DLL files it was looking for in there.

So why was the binary not finding them?

Turns out, I had only recently installed mingw (the C/C++ compiler), which did update the PATH as I saw, but I had not restarted my Windows Terminal window. (You can't just open a new tab. You have to close the whole friggin application! Geez.) Simply restarting the Windows Terminal and running the binary again fixed it.

Anyway, now I remember why I don't dev on Windows.

Hope that helps someone.
