### ISSUE TITLE
Add docs about CI in Guides

### ISSUE THREAD

**Issue by Maicarons2022** [wailsapp/wails#2308]
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

# Add docs about CI in Guides
---
Hello, developer,

I think we should add a document about CI building.  
We can write examples for each CI product. Or give the users some certain hints.  
Just as a tip, like `Routing`.

### Self-service

- [x] I'd be willing to address this documentation request myself.

**Comment by Maicarons2022** [comment]
https://github.com/Maicarons2022/autocorrectAir/blob/master/.github/workflows/wailsbuild.yml

that's mine

**Comment by gwynforthewyn** [comment]
Just for a perspective, in order to figure out how to build v2 of the wails cli correctly, I went and read the github CI files. 

I had thought this morning about opening a docs PR against [the website's contributing docs ](https://wails.io/community-guide/#ways-of-contributing) (I'm assuming this is available as a github repo somewhere) just telling other folks "Hey - the canonical way of understanding how to build wails is the github CI files" - this way the github CI files can be updated freely without the documentation becoming stale.

**Comment by leaanthony** [comment]
It has become apparent over time that the approach of trying to hide the complexities of building desktop apps for multiple targets is too inflexible for a chunk of Devs. I believe we can have the best of both worlds. I'll write a blog post about it tonight. Why am I mentioning this? Because the build system is going to change.

**Comment by daisukixci** [comment]
Hi @leaanthony, did you ended writing that blog post ?

**Comment by leaanthony** [comment]
No, but there's a PR up for it.

**Comment by mmghv** [comment]
@leaanthony I think this should be closed as implemented in #2879

**Comment by leaanthony** [comment]
@Maicarons2022 let us know if the above PR doesn't satisfy this ticket 👍
