### ISSUE TITLE
Distribute files and access it

### ISSUE THREAD

**Issue by thepabloaguilar** [wailsapp/wails#2473]
Sorry if this question is already answered but I couldn't find anywhere (GitHub Issues & Docs)! 
I'm building an app which relies on a binary executable to work 'cause behind the scene that executable is called to execute the commands and I want to distribute the app with binary file and then access it somehow from the Go side.

How can I do that?

**Comment by stffabi** [comment]
Thanks for using Wails and joining our community.

This is more of a general Go question rather than something that is specific to Wails. There's the [`go:embed`](https://pkg.go.dev/embed) directive which allows you to embed any file into your binary.
Basically you need to embed your external binary then write it to the filesystem and execute. You should be able to find a lot of guides on the internet how to use that.

Please also feel free to join us on discord, which is a great place to ask questions about how to to things with Wails and also Go.

**Comment by thepabloaguilar** [comment]
@stffabi I have a few problems using `go:embed` for binary files, also, my question is about __wails__! Maybe the wording could cause confusion, the question is: How wails support distributing files through builds (Windows & Mac)? And how to access them?

**Comment by mclxly** [comment]
I need this feature too, just like in Tauri: https://tauri.app/v1/guides/building/resources/

```json
{
  "tauri": {
    "bundle": {
      "resources": [
        "/absolute/path/to/textfile.txt",
        "relative/path/to/jsonfile.json",
        "resources/*"
      ]
    },
    "allowlist": {
      "fs": {
        "scope": ["$RESOURCE/*"]
      }
    }
  }
}
```

**Comment by leaanthony** [comment]
https://blog.jetbrains.com/go/2021/06/09/how-to-use-go-embed-in-go-1-16/

**Comment by mclxly** [comment]
> https://blog.jetbrains.com/go/2021/06/09/how-to-use-go-embed-in-go-1-16/

@leaanthony As far as i know, //go:embed only serve for **static** files. 

In my case, I want to attach a json file which for reading & **writing** system setting.

**Comment by leaanthony** [comment]
You write it out to a config location if it doesn't exist and write there.

**Comment by dingshaohua-com** [comment]
i need too
