### ISSUE TITLE
does  Title not supported Chinese

### ISSUE THREAD

**Issue by sixinyiyu** [wailsapp/wails#261]
app := wails.CreateApp(&wails.AppConfig{
		Width: 1024,
		Height: 768,
		Title: "xx 桌面客户端",
	})

go   1.13
gomodel on
system windows 10 64

![image](https://user-images.githubusercontent.com/3435446/67275174-9cb7ce80-f4f4-11e9-946d-3cf148f51339.png)

**Comment by leaanthony** [comment]
Hi @sixinyiyu - this is a known bug and there's already a couple of tickets open for it. Please see #259 for a temporary fix. I'm looking at getting auto-detection for Windows built into the framework as it is not an issue for Linux or Mac.

**Comment by leaanthony** [comment]
Hi. I've created a fix that I can't fully test locally. Could you please see if your original code works with this version please?
`wails update -pre` should update you to v0.18.6-pre with the fix 🤞

**Comment by scshin0572** [comment]
If I use only Korean, it works, but I use Korean and English together, it works abnormally.

The cause of this problem is Webview does not use Windows API as a UNICODE environment.
So I modified it to convert UTF-8 to UTF-16 inside Webview.

I have attached the modified files.

[webview.zip](https://github.com/wailsapp/wails/files/3766800/webview.zip)

**Comment by leaanthony** [comment]
Please update to the latest pre-release and let me know if that now works for you:

`wails update -pre`

**Comment by leaanthony** [comment]
Will revisit after v1

**Comment by leaanthony** [comment]
This has been fixed in V2
