### ISSUE TITLE
Is it possible to create a VSCode extension using Wails?

### ISSUE THREAD

**Issue by tnfssc** [wailsapp/wails#2626]
### Describe the solution you'd like

I want to build a VSCode extension, and a standalone application with same functionality. I know that VSCode has WebView support. So, I was wondering if it was possible to render the UI in VSCode's webview and run the backend in a thread or a process.

**Comment by airtonix** [comment]
I feel like the answer is: No. 

Because: Wails has to inject some runtime js into the clientside html file loaded into the "webview"


side note: 

You used the word "webview" (like I did). was that because myself and you are too lazy to write the actual name of the lib used on all three platforms? 

Or did you only plan to create a vscode extension that works on Windows?

**Comment by leaanthony** [comment]
Thanks for asking this. I don't believe it's possible and I doubt it will never be a priority either. Feel free to reopen if you feel there's anything else to discuss 👍
