### ISSUE TITLE
Why do backend requests get slower and slower when called in big batches?

### ISSUE THREAD

**Issue by Dima-369** [wailsapp/wails#3076]
### Description

I wondered about an application like a file explorer where one backend call is done per file. Which can easily end up in dozens of dozens of backend calls depending on the directory viewed.

While testing this, I noticed a certain delay, I tried to reproduce like this:

I also see this delay in tauri, but there I have to use `fetch()` which scales terribly with many, many backend calls, regardless how quick the backend responds. In tauri is just so much slower which is no fun.

Here is a video showing the behavior in wails:

https://github.com/wailsapp/wails/assets/15002298/dd2d3fbc-43c7-4818-86a6-a5dfee4fba87

### To Reproduce

I used this to setup wails

```bash
wails init -n wails-vanilla -t vanilla
```

And I modified `main.js` to this:

```html
import "./style.css";
import "./app.css";

import logo from "./assets/images/logo-universal.png";
import { Greet } from "../wailsjs/go/main/App";

document.querySelector("#app").innerHTML = `
    <img id="logo" class="logo">
      <p class="result" id="result">Please enter your name below 👇</p>
      <div class="input-box" id="input">
        <input class="input" id="name" type="text" autocomplete="off" />
        <button class="btn" onclick="greet(1)">1 time</button>
       <button class="btn" onclick="greet(20)">20 times</button>
      </div>
    </div>
`;
document.getElementById("logo").src = logo;

let nameElement = document.getElementById("name");
nameElement.focus();
let resultElement = document.getElementById("result");

window.greet = function (n) {
  let name = nameElement.value;
  try {
    for (let i = 0; i < n; i++) {
      const start = new Date().getTime();
      Greet(name)
        .then((result) => {
          const newTime = new Date().getTime() - start + "ms";
          resultElement.innerText = resultElement.innerText + newTime + " , ";
        })
        .catch((err) => {
          console.error(err);
        });
    }
  } catch (err) {
    console.error(err);
  }
};

```

The slowdown is seen on both `wails dev` and on building and launching the app.

Is this something which can be improved upon?

### Expected behaviour

I would not expect the batches of backend calls to get slower and slower, but stay stable.

Since even when one waits after sending many requests, the slowdown seems to accumulate.

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.0     |
| ID           | 23A344   |
| Go Version   | go1.21.2 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version        |
| Xcode command line tools  | N/A          | Installed | 2399           |
| Nodejs                    | N/A          | Installed | 21.2.0         |
| npm                       | N/A          | Installed | 10.2.3         |
| *Xcode                    | N/A          | Installed | 15.0 (15A240d) |
| *upx                      | N/A          | Available |                |
| *nsis                     | N/A          | Available |                |
└─────────────────────── * - Optional Dependency ───────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
```

### Additional context

Thanks for wails :)

**Comment by danielcasler** [comment]
I mean no disrespect but you may want to learn about how JavaScript, particularly the event loop works. This video should get you started: https://www.youtube.com/watch?v=8aGhZQkoFbQ

JavaScript operates within a single-threaded event loop, which manages the execution of all script operations. When you execute a loop that fires off multiple asynchronous requests – as in your case with 20 calls to the Greet function – these requests are dispatched almost simultaneously. However, they don't get processed immediately. Instead, they're queued in the event loop to be handled sequentially after the current script execution, including the loop, finishes.

The key point here is that the start time you're recording for each request is captured almost at the same moment for all requests, as they are all queued up during the loop execution. The event loop then processes these requests one by one. As a result, each asynchronous call must wait for its turn to be processed, leading to a cumulative delay.

This sequential processing is crucial to understand: despite initiating requests simultaneously, their resolution is staggered. Each request waits for the previous one to complete, extending the total time required to handle all requests. Furthermore, frequent DOM updates within each request's resolution can exacerbate the delay, as repeated DOM manipulations are computationally expensive. This combination of queued asynchronous requests and frequent DOM updates contributes to the overall slower performance when the function is called 20 times.

**Comment by Dima-369** [comment]
@danielcasler Thank you for your detailed answer 🙂

Still, I am struggling to understand why the delay adds up and then never goes down. Say, I spam my code above until I reach 100 ms as seen in the DOM. Then I wait a minute and click the `20` button again. Why is there still this hefty delay? (regardless if the DOM is modified or not) - it just sums up and never goes away. My issue is not about spamming the `20` button 100x times and expecting the responses to come in just as quick.

Because if I do the same code in JavaScript without using `Greet(name)` and just using `fetch()`, I do not see this behavior. If I spam the `20` button (even to the point when a response takes 30 seconds to respond), then wait a minute (or less until the responses are all processed and I suppose the GC kicks in since the page is laggy at that point), click the `20` button again, there is no added delay. It is still back to pretty much exact the same speed the first time I click the button. This is not the case in my video above and what surprises me here.

Am I not understanding how `Greet()` works under the hood, compared to how `fetch()` works? Maybe you know why this happens?

**Comment by danielcasler** [comment]
@Dima-369 
To delve deeper into understanding this, it's essential that we revise and enhance your original code. This approach will allow us to isolate specific aspects of the functionality and more accurately pinpoint potential issues.

In the following code we encapsulate each call to the Greet function within its own asynchronous function (greetAndMeasure). This allows each Greet call to be handled independently, along with its own timing and error handling. 

`let nameElement = document.getElementById("name");
nameElement.focus();
let resultElement = document.getElementById("result");

async function greetAndMeasure(name, i) {
  const start = new Date().getTime();
  Greet(name)
    .then((result) => {
      const timeTaken = new Date().getTime() - start;
      resultElement.innerText += `${timeTaken}ms\n`;
    })
    .catch((err) => {
      console.error(`Error in call ${i}:`, err);
      resultElement.innerText += `Error, `;
    });
}

window.greet = function (n) {
  let name = nameElement.value;
  for (let i = 0; i < n; i++) {
    greetAndMeasure(name, i);
  }
};
`

When I run this version and spam 20, the completion time of the last request does consistently grow, even with a 10 second delays between batches.

Now, with the following code, which I consider to be a more correct implementation, everything works as one would expect.

`let nameElement = document.getElementById("name");
nameElement.focus();
let resultElement = document.getElementById("result");

async function greetAsync(name, i) {
  const start = new Date().getTime();
  try {
    const result = await Greet(name);
    const timeTaken = new Date().getTime() - start;
    return `${timeTaken}ms`;
  } catch (err) {
    console.error(err);
    return `Error in call ${i}: ${err.message}`;
  }
}

window.greet = async function (n) {
  let name = nameElement.value;
  let results = [];

  for (let i = 0; i < n; i++) {
    results.push(greetAsync(name, i));
  }

  Promise.all(results)
    .then((times) => {
      resultElement.innerText += times.join(" , ") + " , ";
    })
    .catch((err) => {
      console.error("Error processing batch:", err);
    });
};
`  
What this tells me is that the issue likely lies within the intricacies of the JavaScript runtime, particularly in how it manages and schedules asynchronous tasks. The distinct behaviors observed between the two code versions suggest that the event loop's handling of queued tasks, memory management, and possibly internal optimizations specific to JavaScript engines, are key factors influencing the performance discrepancies. The runtime's approach to handling multiple simultaneous asynchronous calls, as well as its strategies for resource allocation and garbage collection, seem to be contributing to the varying response times. These insights point towards a deeper dive into the JavaScript engine's operational mechanics, which could unveil more specific reasons behind the observed performance patterns.

It's unlikely the issue lies with Wails as we'd also see performance degradation using Promise.all.

**Comment by Dima-369** [comment]
> It's unlikely the issue lies with Wails (Go) as we'd also see performance degradation using Promise.all.

That sums it up very nicely and is a key takeaway here.

Thank you for taking your time and for your investigation! This answers all my questions 👍 

I definitely consider Wails for a project of mine now since I was genuinely worried that if I spam the backend the requests get slower and slower as I observed - not realizing that my test code to check for viability of my project was inadequate.

**Comment by danielcasler** [comment]
@Dima-369 For fun with the Promise.all option I increased the batch size to 10,000. It takes 80ms to for the first result due to the time it takes for these requests to be queued and for the JavaScript event loop to begin processing them. They all complete in less than 200 ms. Multiple 10,000 batches do lead to a 25ms difference in the last request completing.

**Comment by Dima-369** [comment]
> 10,000 requests in 200ms between JS and Go is pretty fast, no? Tauri is many times worse.

Yes, indeed. That's really something ⚡ 

Time to beef up my JavaScript and Go knowledge again now 😉

**Comment by danielcasler** [comment]
10,000 requests without Promise.all blows the app up lol

**Comment by leaanthony** [comment]
> I definitely consider Wails for a project of mine now since I was genuinely worried that if I spam the backend the requests get slower and slower as I observed - not realizing that my test code to check for viability of my project was inadequate.

Just to mention that the current method encodes raw json, sends it to Go and decodes it there. In the example given, it sends the text in the result div. This gets bigger over time so naturally the request gets bigger, and slower, the more it's run. Try just calling that method with a fixed size string and see how many requests you get.

We are talking about just exposing a raw string pipe so that you can choose what you want to send over it and how to encode it. Using what's there.... in general, if you are performing a lot of calls in quick succession then there's a good chance it's the wrong design.
