### ISSUE TITLE
Support Distribution 'KaOS'

### ISSUE THREAD

**Issue by OfficialBoyfriend** [wailsapp/wails#328]
**Description**
Distribution 'kaos' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.1 |
| Go Version    | go1.13.5 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | kaos |
| Distribution Name   | KaOS |
| Distribution Version   | 2020 |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

**Comment by bh90210** [comment]
hello @bianxl-yy 
please stay tuned a supporting PR is coming shortly!

**Comment by bh90210** [comment]
ok I am looking in to it and it seems like KaOS doesn't have a webkitgtk package?

https://forum.kaosx.us/d/1817-package-from-aur/7

also there is no docker image so I can not investigate more I'm afraid.

**Comment by bianxl-yy** [comment]
Ok, got it. Thank you for your efforts.

**Comment by bh90210** [comment]
@leaanthony 
what we can do for situations that the distro can not be supported due to libraries missing, like KaOS. is to provide a. a guide and b. a docker image with all tooling and develop/test via running the gui app inside docker.

resources:
https://forums.docker.com/t/still-not-sure-how-to-run-gui-apps-in-docker-containers/79103/2
https://medium.com/@SaravSun/running-gui-applications-inside-docker-containers-83d65c0db110
https://www.youtube.com/watch?v=Jp58Osb1uFo

**Comment by leaanthony** [comment]
For v1, there's nothing we can do about it. The platform doesn't support
the libs. Docker plus AppImages is probably the answer.

**Comment by bianxl-yy** [comment]
Good idea, I will try it.

**Comment by bh90210** [comment]
@leaanthony my proposal here wasn't for wails built apps to run on unspported distros
but rather enable the development of wails apps on such distros.
