### ISSUE TITLE
Build with just production webapp url

### ISSUE THREAD

**Issue by RichardLindhout** [wailsapp/wails#3286]
### Is your feature request related to a problem? Please describe.

I want to minimize the releases of the native app

### Describe the solution you'd like

An option to provide a production url in wails configuration, so webapp only updates can be done without updating the native application

### Describe alternatives you've considered

Building wails app for every webapp only change

**Comment by stffabi** [comment]
Thanks for using Wails and reporting this.

This can already be achieved in different ways, I've outlined them [here](https://github.com/wailsapp/wails/discussions/1361#discussioncomment-2660071) some time ago.

Feel free to join the discussion over there if you need any help or information.

I'm going to close this enhancement request because it's already possible to achieve this with the current provided APIs.

**Comment by RichardLindhout** [comment]
Thanks for the hints @stffabi !
