### ISSUE TITLE
Request: Example/Template

### ISSUE THREAD

**Issue by tlscipher** [wailsapp/wails#336]
For those of us new to React, Vue, and Angular, I feel an example repo or project template with vanilla js/html/css would be quite helpful. Thanks.

**Comment by bh90210** [comment]
hello @mehtaabGill 
at the moment wails works by grabbing a `.js` and a `.css` files produced from any front and renders them.
So in order to work you need to use webpack in the very least.

We tried to figure a way to have an easy solution/alternative but it was far from pure html/js. We had to use node/webpack again.

albeit, we are in the workings of wails v2 where this feature will be available by default (no webpack, no node, you will be able to just use your hand-coded html/js front)
I have no idea when it will be ready at least for testing.

**Comment by bh90210** [comment]
#304

**Comment by leaanthony** [comment]
As Byron said, this will be coming in v2. If you really want to try to roll your own, just replace the js and CSS file paths in a generated main.go to your own and remember to ensure that you use `@wailsapp/runtime` and use the `Init` method to callback to your js.

My humble opinion is that of all your options, learning Vue is the easiest. It really will make your life easier.
