### ISSUE TITLE
OpenFileDialog Call Crashes Application

### ISSUE THREAD

**Issue by CaptainFallaway** [wailsapp/wails#3726]
### Description

I'm making a project where a file needs to be loaded and I'm using `runtime.OpenFileDialog` and when my frontend calls my `OpenFileDialog` function bound to my app interface it just crashes and gives me a long error that I myself cannot debug nor understand at all.

I am developing this application on two devices one running debian trixie with go version 1.23 and the other running windows 11 with go 1.23. On my linux installation it works with no problems but when I run the exact same source code on my windows device it dumps me this long error that I'll post below in a pastebin.

https://pastebin.com/uDnayxFc

I should also mention that I'm using Wails version 2.9.1 and when I run the exact same code in go version 1.22.6 it just works...

### To Reproduce

Run windows 11 23H2

1. Clone my XDH application from github (sorry not sorry)
2. Run with `wails dev` (wails ver 2.9.1 & go ver 1.23)
3. Click on the 'Open File' button on the top right

Or just use the `runtime.OpenFileDialog` function with these options:

```go
var dialogOptions = runtime.OpenDialogOptions{
	ShowHiddenFiles: true,
	Filters: []runtime.FileFilter{
		{
			DisplayName: "Excel or Csv files",
			Pattern:     "*.xlsx;*.xls;*.csv",
		},
	},
}
```

### Expected behaviour

The `runtime.OpenFileDialog` should open the windows explorer dialog window so that the user of my application can select a file.

### Attempted Fixes

Run with go version 1.22.6 installed and wails 2.9.1 which works perfectly fine.

I've also tried:

- `go clean -cache`
- `go clean -modcache`

### System Details

```shell
# Wails
Version | v2.9.1

# System
┌────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Pro                                          |
| Version      | 2009 (Build: 22631)                                     |
| ID           | 23H2                                                    |
| Go Version   | go1.23.0                                                |
| Platform     | windows                                                 |
| Architecture | amd64                                                   |
| CPU          | Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz                |
| GPU          | NVIDIA GeForce GTX 1080 (NVIDIA) - Driver: 32.0.15.6094 |
| Memory       | 32GB                                                    |
└────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 128.0.2739.54 |
| Nodejs     | N/A          | Installed | 20.16.0       |
| npm        | N/A          | Installed | 10.8.2        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘
```

**Comment by levinit** [comment]
same as #3681, it will be fixed next release

**Comment by CaptainFallaway** [comment]
Thanks for quick response

**Comment by stitpragya22** [comment]
this issue is stil there. 
I got erro today while opening json file 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.PowerToys.PreviewHandler.Monaco.MonacoPreviewHandlerControl.<>c__DisplayClass13_0`1.<<DoPreview>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 9.0.0.0
    Location: C:\Users\info\AppData\Local\PowerToys\System.Private.CoreLib.dll
----------------------------------------
PowerToys.MonacoPreviewHandler
    Assembly Version: 0.91.1.0
    Location: C:\Users\info\AppData\Local\PowerToys\PowerToys.MonacoPreviewHandler.dll
----------------------------------------
System.Runtime
    Assembly Version: 9.0.0.0
    Location: C:\Users\info\AppData\Local\PowerToys\System.Runtime.dll
----------------------------------------
WinRT.Runtime
    Assembly Version: 2.2.0.0
