### ISSUE TITLE
v2.9.2 can't build runnable .app on macOS when 'name' and 'outputfilename' are different

### ISSUE THREAD

**Issue by tramamte** [wailsapp/wails#3786]
### Description

from v2.9.2, on macOS, wails uses 'outputfilename' value to make a binary file.
But still the CFBundleExecutable is set to {{.Name}} in the Info.plist. So, when 'name' and 'outputfilename' are different, the .app cannot be executed.

<img width="250" alt="Screenshot 2024-09-27 at 1 49 32 PM" src="https://github.com/user-attachments/assets/2004120f-8081-4500-bb53-5f8fffb836f0">

The CFBundleExecutable should be set to 'outputfilename'. The 'buildassets', however, only exports 'Name' and 'Info'.
https://github.com/wailsapp/wails/blob/master/v2/pkg/buildassets/buildassets.go#L109

**Comment by leaanthony** [comment]
Nice catch. Are you able to raise a PR for this?

**Comment by nickisworking** [comment]
@leaanthony
Hello, I'm a team member of @tramamte  and I would like to raise a PR for  this issue.

It seems very clear, but I'll leave a few additional comments according to the contribution guide.

1. First of all, I have confirmed that the bug is reproducible in my environment as well.
- If th`name` and `outputfilename` in `wails.json` are different, the app cannot be executed.

<img width="446" alt="image" src="https://github.com/user-attachments/assets/371f5bbd-7be7-475b-95fc-c04ab35c0ac1">

<img width="668" alt="image" src="https://github.com/user-attachments/assets/e7d856f3-043f-4a56-add1-6e9ed0cb1438">

2. The result of wails doctor is as follows
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/65ce8d12-3b6c-463b-8763-e8e95c02a515">

**Comment by raguay** [comment]
I'm also having this issue. I can't use Modal File Manager anymore since I recompiled it using 2.9.2 and it will not run. It says the program is incomplete.

**Comment by raguay** [comment]
I was able to fix it as above. Make the program name and output name the same. Interesting.

**Comment by tramamte** [comment]
@raguay As I mentioned above, there is no issue, if the 'name' and 'outputfilename' are same. And because wails v2.9.1 ignored 'outputfilename', it also had no issue.

**Comment by nickisworking** [comment]
@raguay @tramamte 

Yes. Plus, I have also figured out that It works well even if the case is different. e.g) test/Test

**Comment by leaanthony** [comment]
I think this is something we should fix. Should be no need to manually keep these the same
