### ISSUE TITLE
Is it possible to access http://wails.localhost/ via a browser after compilation?

### ISSUE THREAD

**Issue by askie** [wailsapp/wails#3844]
### Is your feature request related to a problem? Please describe.

I hope that after compiling, the exe file will act as a server. Any computer in the LAN can visit http://wails.localhost/ through a browser to access and use the provided services normally.

### Describe the solution you'd like

I hope that after compiling, the exe file will act as a server. Any computer in the LAN can visit http://wails.localhost/ through a browser to access and use the provided services normally.

**Comment by Dexus** [comment]
You can use any server framework as you like, to make your website serving via wails. 

Just use gin, iris, or what ever and run it within your wails app. But Wails it self is no webser that will provide what you like to do.

**Comment by ThibeauMaerevoet** [comment]
I would like to drop this transcript of discord here, as I recently had a similar question:

`Atterpac — 10/18/2024 11:05 PM
Theres an experimental branch that supports a hyrbid of web and desktop [branch](https://github.com/wailsapp/wails/tree/feature/add_support_for_server_and_hybrid)
GitHub
[GitHub - wailsapp/wails at feature/add_support_for_server_and_hybrid](https://github.com/wailsapp/wails/tree/feature/add_support_for_server_and_hybrid)
Create beautiful applications using Go. Contribute to wailsapp/wails development by creating an account on GitHub.
GitHub - wailsapp/wails at feature/add_support_for_server_and_hybrid
Thibeau M.
OP
 — 10/18/2024 11:55 PM
Interesting. Didn't find this before... will take a look.
Thank you
Thibeau M.
OP
 — Today at 11:25 AM
@Atterpac do you know is they also wrote some docs on it? I'm not too experienced and it would be great to read something rather than trying to figure out the code 😄
Atterpac — Today at 3:31 PM
No docs as it's experiential if I remember correctly there's a server.Options added to the options to set your port and such and then you build with -tags=exp and then either hybrid or server tag depending if you want a desktop and webpage or just the webpage
V3 is attempting to have a similar setup via a plugin but still WIP`
