### ISSUE TITLE
windows 10    Wails v1.6.0-pre5 ，wails serve cmd not worked

### ISSUE THREAD

**Issue by zhuqiyun** [wailsapp/wails#430]
#####################################################
     If you have a technical issue, please do not open a bug this way! 
                      Please use the `wails issue` command!                          
#####################################################

**Description**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**
Please provide your platform, GO version and variables, etc

**Additional context**

**Comment by zhuqiyun** [comment]
WebSocket connection to 'ws://localhost:34115/bridge' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by tmclane** [comment]
Do you have a personal firewall running that might be blocking communications?

**Comment by leaanthony** [comment]
Confirmed this issue. Sits on the "waiting for backend" spinner. Console log shows websocket connection error.

**Comment by leaanthony** [comment]
Narrowed this down to commit [c66e9cba5a0bf609320972c298baf219142186d3](https://github.com/wailsapp/wails/commit/c66e9cba5a0bf609320972c298baf219142186d3). Looks like a combination of `runtime.GOOS` being used instead of `projectOptions.Platform` and compiling the application in prod mode instead of build more. Still investigating.

**Comment by leaanthony** [comment]
Pushed a fix #433 - Please update to latest pre-release `wails update -pre`.
