### ISSUE TITLE
Can not use <video >

### ISSUE THREAD

**Issue by mostend** [wailsapp/wails#456]
Hi,

 I found that I couldn't play web video when I used the video tag. 

wails : 1.6.0
os : windows 10 
gcc : gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
vue : vue 2.0

**Comment by ilgityildirim** [comment]
@waini1110 I have to confirm this but it is likely due to engine behind Windows which is based on IE 11 and you can't use `<video>` tags there; https://www.caniuse.com/#search=video. However this is just a guess, I'd have to check it out myself to confirm.

**Comment by ilgityildirim** [comment]
@waini1110 I have to confirm this but it is likely due to engine behind Windows which is based on IE 11 and it seems it is not supported out of the box. I have to say I haven't tried it with Wails something like this yet.

You can try to add codec to your source such as;
`<source src="video.mp4" type='video/mp4; codecs="H.264/MPEG-4" '>`

As it seems IE11 requires H.264/MPEG-4 codec to make the videos work.

**Comment by waini1110** [comment]
Thanks for your reply.  I found must be add  codecs="H.264/MPEG-4". 
if not added we can saw the image, but can not play.

**Comment by ilgityildirim** [comment]
@leaanthony I guess this is safe to close.

**Comment by leaanthony** [comment]
👍
