### ISSUE TITLE
Modify build fo macOS app bundles

### ISSUE THREAD

**Issue by WizardOfCodez** [wailsapp/wails#474]
Is there a way to automatically specify parameters that should appear in OSX app bundles info.plist?

We need the key ``CFBundleURLTypes`` to bind our wails app to a custom protocol handler. We can edit the file by hand of course but it would be nice to do this while running ``wails build -p``

**Comment by leaanthony** [comment]
Not at this point, but we could think about how that could work? For the windows builds we've recently changed it so the manifest files are kept after the initial build so that they could be modified this way. Perhaps this would be a solution? Leave a copy in the project root and if it finds one there it uses it instead of the default one?

**Comment by CrackDavid** [comment]
I also guess this would be a good solution. Luckily there is a gist which shows on how to do the build process. It seems that he is also working with an boilerplate: https://gist.github.com/tzmartin/25f33c04b4b663392acaa9cff2b7dfb4

**Comment by leaanthony** [comment]
I'll get onto this shortly!

**Comment by CrackDavid** [comment]
That works pretty well! I just put my Info.plist into the project folder. It automatically gets packed into the app - perfect solution for me!
