### ISSUE TITLE
[Enhancement] Minimize app to the hidden icon area on taskbar

### ISSUE THREAD

**Issue by hazymoon22** [wailsapp/wails#514]
**ISSUES**
A lot of desktop apps can be minimized to the hidden icon area without displaying app icon on the taskbar. This works well with lightweight app that run in background a lot. I can't find how to hide or show the app window and icon using wails.

**SUGGESTION**
Add a minimized to hidden icon area feature.

**Comment by leaanthony** [comment]
This is pretty tricky as GNOME and gtk have dropped the ides of the tray icon.

**Comment by leaanthony** [comment]
I just re-read this and I think you just want hide and show? What kind of desktop app would use that vs having an icon to hide and show in the tray?

**Comment by misitebao** [comment]
If your requirements are not very strict, you can try to combine with the following library to achieve ingenious implementation | 如如果你的要求不是非常严苛的话，可以尝试与下面这个库结合，从而巧妙的实现
https://github.com/getlantern/systray

**Comment by leaanthony** [comment]
Impossible as they both want to own the main thread.

**Comment by Fuih** [comment]
I'm thinking like a desktop app that running in the background to monitor something, and notify the user if a condition is satisfied (like cpu temperature monitor). When the user want to change some settings, they can double click the icon on the tray to make the app appear. Of course it's not something that is **required**, the app can just show on desktop like a normal app.  It just seems more clean to be able to hide it since the user rarely need to look at it.

**Comment by leaanthony** [comment]
If you can find a good way of doing this on Linux, we can look.at it. Even electron does not guarantee that the app will be visible in a tray as some DEs don't have a tray and some (GNOME) actively deprecated it.

**Comment by leaanthony** [comment]
I would also be keen to hear what you think the API would look like for this.

**Comment by leaanthony** [comment]
This won't be in V1 and maybe in V2.
