### ISSUE TITLE
Basic Packaging command for Debian (and other debian based distros)

### ISSUE THREAD

**Issue by sarthakpranesh** [wailsapp/wails#559]
**Is your feature request related to a problem? Please describe.**
There are packaging commands for Mac OS and Windows, but none for any Linux distribution.

**Describe the solution you'd like**
I was able to package a relatively simple .deb package for [cpuRoller](https://github.com/sarthakpranesh/CpuRoller/tree/master) and I have converted all the steps into a bash script program [debian-build.sh](https://github.com/sarthakpranesh/CpuRoller/blob/master/debian-build.sh). I was thinking it would be nice to have such basic packaging for common Linux distros (such as Debian based distros)

Creating this issue for further discussion

**Comment by leaanthony** [comment]
Hi @sarthakpranesh! Goo job on getting the deb built. Packaging for linux is pretty hard given all the various configurations and package managers. I feel like if we support deb, we'd have to support a lot of the other formats and there doesn't seem to be an easy way to do that. The option I'm looking at for V2 is flatpak as that's widely supported. Thanks for your time!

**Comment by sarthakpranesh** [comment]
Hey @leaanthony, yeah Flatpak sounds good to me. I was just wondering if AppImage can also be a possibility. Really looking forward to this.

**Comment by rogchap** [comment]
I tried getting an AppImage working with V1 but had a hard time getting webkitgtk included/linked correctly; the AppImage was around 60MB compared to the 8MB binary, so I gave up.

**Comment by leaanthony** [comment]
I did some experiments with AppInage for v2. Got it working but it's pretty
bad and I'm almost certainly favouring flatpak at this point.

**Comment by sarthakpranesh** [comment]
Yeah, Flatpak will be great for packaging for Linux. Can't wait for v2 now :rocket:

**Comment by bh90210** [comment]
Awesome news for v2 + flatpack!

Appimages seems to be the most popular, at least for software I am downloading anyway, but flatpack is equally fine! 
the fact that there will be some parity with win & mac is a great news! :tada:  

_Though I maintain my position that for more complicated scenarios devs will opt using other tools to package/deliver for various distros so the overhead of wails maintaining 182 different distros seems as always somehow out-of-scope/unrealistic._

**Comment by lil5** [comment]
https://github.com/fyne-io/flatpak_demo/blob/main/README.md

This might help.

**Comment by leaanthony** [comment]
@ianmjones has also done some amazing work with packaging on Linux

**Comment by ianmjones** [comment]
I packaged a Wails v1 app as a Flatpack and Snap:

https://github.com/ianmjones/wails-test

You can see the warts-n-all exploration process that lead to that repo in the following YouTube playlist:

https://www.youtube.com/playlist?list=PLDWtdmaxq1fc0-LP9jlCVItkkJWq_OMyd

I haven't attempted packaging a Wails v2 app yet, but will do once I get to the point in my current project whereby I have a GUI app to package!

Like @bh90210, I also believe it's best that packaging be left to the developer rather than be built into the `wails` CLI, there's just too many potential targets. But getting some recipe repos together or maybe integrating some sort of templated packager or example recipe generator into the CLI would be good.
