### ISSUE TITLE
`wails build` Stuck at "Ensuring Dependencies are up to date..."

### ISSUE THREAD

**Issue by asdptkt** [wailsapp/wails#87]
**Description**

Like the title says. `wails build` stuck at that stage. And this is for the freshly initialized wails, generated from `wails init`.

**To Reproduce**
Steps to reproduce the behaviour:
1. `wails init`
2. `cd myprojectname`
3. `wails build`

**Expected behaviour**
Build success.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.13.3 |
| Go Version    | go1.12.5 |
| Platform      | darwin |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment]
Hi @asdptkt. Seems like my reply never got sent. The only thing I can think this issue might have been your internet connection? I am unable to reproduce this. Have you tried again since?

<img width="1438" alt="Screen Shot 2019-05-13 at 8 06 09 pm" src="https://user-images.githubusercontent.com/1943904/57735787-26af7000-76e9-11e9-86cd-11cf16fb659c.png">

**Comment by asdptkt** [comment]
> Hi @asdptkt. Seems like my reply never got sent. The only thing I can think this issue might have been your internet connection? I am unable to reproduce this. Have you tried again since?
> 
> <img alt="Screen Shot 2019-05-13 at 8 06 09 pm" width="1438" src="https://user-images.githubusercontent.com/1943904/57735787-26af7000-76e9-11e9-86cd-11cf16fb659c.png">

Hello, turned out it was my DNS acting up.

Consider this issue solved. Thank you.

Also, adding verbose mode to wails CLI would be great so user issue this could be easily solved by the user.

**Comment by leaanthony** [comment]
Great suggestion. If you open a ticket you'll get notified when it's done
